name: Auto build for windows

on:
  push:
    branches: [ '*' ]
  pull_request:
    branches: [ '*' ]

jobs:
  pyinstaller:
    runs-on: windows-2022
    steps:
    - name: Setup python
      uses: actions/setup-python@v4
      with:
          python-version: '3.12'
          architecture: x64
    - uses: actions/checkout@v3
    - name: Install dependencies
      run: |
        pip install pyinstaller httpx[http2]
        pip install -r requirements.txt
    - name: Package Application
      run: |
        pyinstaller accesser.spec
      env:
        PYTHONOPTIMIZE: 1
    - uses: actions/upload-artifact@v3
      with:
        path: ./dist/
