name: Auto build for windows

on:
  push:
    branches: [ '*' ]
  pull_request:
    branches: [ '*' ]

jobs:
  windows:
    runs-on: windows-2022
    steps:
    - name: Setup python
      uses: actions/setup-python@v4
      with:
          python-version: '3.12'
          architecture: x64
    - uses: actions/checkout@v3
    - name: Install dependencies
      run: |
        pip install pyinstaller dnspython[doh,doq]
        pip install -r requirements.txt
    - name: Package Application
      run: |
        pyinstaller accesser.spec
      env:
        PYTHONOPTIMIZE: 1
    - uses: actions/upload-artifact@v3
      with:
        name: windows
        path: ./dist/
  
  windows-lite:
    runs-on: windows-2022
    steps:
    - name: Setup python
      uses: actions/setup-python@v4
      with:
          python-version: '3.12'
          architecture: x64
    - uses: actions/checkout@v3
    - name: Install dependencies
      run: |
        pip install pyinstaller
        pip install -r requirements.txt
    - name: Package Application
      run: |
        sed -i 's/^ \+\"https/# \"https/' accesser/config.toml
        pyinstaller accesser.spec
      env:
        PYTHONOPTIMIZE: 1
    - uses: actions/upload-artifact@v3
      with:
        name: windows-lite
        path: ./dist/
